id: P001821
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:23:32.595731
source_metadata:
  id: bdr:W3CN4621
  title: ཁྲུས་སོགས་ཉེར་མཁོ་ཕྱོགས་བསྡུས་རིན་ཆེན་བུམ་བཟང་།
  author: ''
  volumes:
    55b89cafe48d439a806cd46564a3f6c7:
      image_group_id: I3CN4623
      title: ''
      volume_number: 1
      total_pages: 306
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
